/**
 * build-assets.mjs — vendor the fonts and icons into docs/assets.
 *
 * Nothing on this site loads from a CDN. Fonts and icons are installed as
 * devDependencies and copied into the repo at build time, so a published page
 * is self-contained and renders identically offline, in CI, and on GitHub
 * Pages.
 *
 *   fonts  — Inter, Barlow Condensed and JetBrains Mono, all SIL Open Font
 *            License 1.1, from the @fontsource packages
 *   icons  — Microsoft's Fluent UI System Icons, MIT licensed, extracted from
 *            @fluentui/svg-icons into one inline <symbol> sprite
 *
 * Run with: npm run assets
 */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MODULES = join(ROOT, 'node_modules');
const ASSETS = join(ROOT, 'docs', 'assets');
const FONT_DIR = join(ASSETS, 'fonts');

/* ------------------------------------------------------------------ fonts */

const FONTS = [
  { pkg: 'inter', family: 'Inter', weights: [400, 500, 600, 700, 800] },
  { pkg: 'barlow-condensed', family: 'Barlow Condensed', weights: [600, 700] },
  { pkg: 'jetbrains-mono', family: 'JetBrains Mono', weights: [500, 700] },
];

function buildFonts() {
  mkdirSync(FONT_DIR, { recursive: true });
  const faces = [];

  for (const { pkg, family, weights } of FONTS) {
    for (const weight of weights) {
      const file = `${pkg}-latin-${weight}-normal.woff2`;
      const from = join(MODULES, '@fontsource', pkg, 'files', file);

      if (!existsSync(from)) {
        console.warn(`  missing font file ${file} — skipped`);
        continue;
      }

      copyFileSync(from, join(FONT_DIR, file));
      faces.push(
        `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: block;\n` +
        `  src: url('fonts/${file}') format('woff2');\n` +
        `}`
      );
    }
  }

  const css =
    `/* Generated by tools/build-assets.mjs — do not edit by hand.\n` +
    `   Inter, Barlow Condensed and JetBrains Mono, SIL Open Font License 1.1.\n` +
    `   Self-hosted: this site loads nothing from a CDN. */\n\n` +
    faces.join('\n\n') + '\n';

  writeFileSync(join(ASSETS, 'fonts.css'), css);
  console.log(`fonts: ${faces.length} faces -> docs/assets/fonts.css`);
}

/* ------------------------------------------------------------------ icons */

/**
 * The sprite. Each entry maps the id used in markup to a Fluent icon file
 * name, so the markup reads as intent ("the RAG panel's icon") rather than as
 * whatever Microsoft happened to call the glyph.
 */
const ICONS = {
  // exam and document furniture
  'certificate': 'ribbon_star_24_regular',
  'clock': 'clock_24_regular',
  'target': 'target_arrow_24_regular',
  'book': 'book_open_24_regular',
  'checklist': 'task_list_ltr_24_regular',
  'check': 'checkmark_circle_24_filled',
  'flag': 'flag_24_regular',
  'lightbulb': 'lightbulb_24_regular',
  'warning': 'warning_24_regular',
  'info': 'info_24_regular',

  // platform
  'layers': 'stack_24_regular',
  'cube': 'cube_24_regular',
  'cloud': 'cloud_24_regular',
  'plug': 'plug_connected_24_regular',
  'code': 'code_24_regular',
  'branch': 'branch_24_regular',
  'gauge': 'gauge_24_regular',
  'lock': 'lock_closed_24_regular',
  'shield': 'shield_checkmark_24_regular',
  'settings': 'settings_24_regular',

  // model and generative work
  'brain': 'brain_circuit_24_regular',
  'bot': 'bot_24_regular',
  'sparkle': 'sparkle_24_regular',
  'flash': 'flash_24_regular',
  'search': 'search_24_regular',
  'database': 'database_24_regular',
  'chat': 'chat_multiple_24_regular',
  'function': 'math_formula_24_regular',
  'globe': 'globe_24_regular',
  'document': 'document_24_regular',
  'beaker': 'beaker_24_regular',
  'chart': 'data_bar_vertical_24_regular',
  'scales': 'scales_24_regular',

  // modalities
  'image': 'image_24_regular',
  'video': 'video_clip_24_regular',
  'mic': 'mic_24_regular',
  'speaker': 'speaker_2_24_regular',
  'text': 'text_paragraph_24_regular',
  'translate': 'translate_24_regular',
  'scan': 'scan_text_24_regular',

  // process
  'route': 'flowchart_24_regular',
  'arrow': 'arrow_right_24_filled',
  'people': 'people_team_24_regular',
  'eye': 'eye_24_regular',
};

/**
 * Fluent ships each icon as a standalone <svg>. Lift the inner markup and the
 * viewBox into a <symbol> so the whole set costs one inline sprite and each
 * use site is a four-attribute <use>.
 */
function toSymbol(id, name) {
  const file = join(MODULES, '@fluentui', 'svg-icons', 'icons', `${name}.svg`);

  if (!existsSync(file)) {
    throw new Error(`icon "${name}" not found — check the name in ICONS`);
  }

  const svg = readFileSync(file, 'utf8');
  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 24 24';
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*fill="[^"]*"/g, '')
    .trim();

  return `<symbol id="i-${id}" viewBox="${viewBox}">${inner}</symbol>`;
}

function buildIcons() {
  const symbols = Object.entries(ICONS).map(([id, name]) => toSymbol(id, name));

  const sprite =
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n` +
    `<!-- Microsoft Fluent UI System Icons, MIT licensed.\n` +
    `     Generated by tools/build-assets.mjs — do not edit by hand. -->\n` +
    symbols.join('\n') + `\n</svg>\n`;

  writeFileSync(join(ASSETS, 'icons.svg'), sprite);
  console.log(`icons: ${symbols.length} symbols -> docs/assets/icons.svg`);
}

/* ---------------------------------------------------------------- licences */

/** The canonical MIT text, for packages that declare MIT but ship no LICENSE. */
function mitText(holder) {
  return `MIT License

Copyright (c) ${holder}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;
}

function copyLicences() {
  const out = join(ROOT, 'THIRD-PARTY-NOTICES.md');
  const parts = [
    '# Third-party notices',
    '',
    'This repository redistributes the following third-party assets. Each is',
    'used under the licence shown, and each licence text is reproduced in full',
    'below. Where a package declares a licence but ships no text, the canonical',
    'text for that licence is reproduced instead.',
    '',
    '| Asset | Package | Licence |',
    '| --- | --- | --- |',
    '| Fluent UI System Icons | `@fluentui/svg-icons` | MIT |',
    '| Inter | `@fontsource/inter` | SIL Open Font License 1.1 |',
    '| Barlow Condensed | `@fontsource/barlow-condensed` | SIL Open Font License 1.1 |',
    '| JetBrains Mono | `@fontsource/jetbrains-mono` | SIL Open Font License 1.1 |',
    '',
  ];

  const sources = [
    ['Fluent UI System Icons (MIT)', join(MODULES, '@fluentui', 'svg-icons', 'LICENSE'),
     mitText('Microsoft Corporation')],
    ['Inter (SIL OFL 1.1)', join(MODULES, '@fontsource', 'inter', 'LICENSE')],
    ['Barlow Condensed (SIL OFL 1.1)', join(MODULES, '@fontsource', 'barlow-condensed', 'LICENSE')],
    ['JetBrains Mono (SIL OFL 1.1)', join(MODULES, '@fontsource', 'jetbrains-mono', 'LICENSE')],
  ];

  // These assets are redistributed, so their licence text has to ship. A
  // missing one used to be skipped silently, which produced a notices file
  // that claimed MIT for the Fluent icons without carrying the text —
  // @fluentui/svg-icons declares MIT in package.json but ships no LICENSE
  // file. Now it falls back to the canonical text, and a genuinely missing
  // licence fails the build.
  let missing = 0;
  for (const [title, path, fallback] of sources) {
    const text = existsSync(path) ? readFileSync(path, 'utf8').trim() : fallback;
    if (!text) {
      console.error(`  no licence text for ${title} — it is redistributed, so this cannot ship`);
      missing++;
      continue;
    }
    parts.push(`## ${title}`, '', '```text', text, '```', '');
  }

  if (missing) process.exit(1);

  writeFileSync(out, parts.join('\n'));
  console.log(`licences: ${sources.length} texts -> THIRD-PARTY-NOTICES.md`);
}

mkdirSync(ASSETS, { recursive: true });
buildFonts();
buildIcons();
copyLicences();
