/**
 * seo.mjs — one source of truth for the site's identity and per-page metadata.
 *
 * Both the generated guide pages and the hand-authored pages pull their head
 * tags from here, so the canonical host, the social card and the structured
 * data can never drift apart between them.
 */

export const SITE = {
  /** No trailing slash. Every canonical and og:url is built from this. */
  origin: 'https://rahulmahadik.github.io',
  base: '/ai-103-certification-study-guide',
  name: 'AI-103 Certification Study Guide',
  /** Used in <title>; the full name eats 32 characters of a 60-char budget. */
  shortName: 'AI-103 Study Guide',
  tagline: 'Developing AI Apps and Agents on Azure',
  author: 'Rahul Mahadik',
  authorUrl: 'https://www.linkedin.com/in/rahulmahadik',
  repo: 'https://github.com/rahulmahadik/ai-103-certification-study-guide',
  locale: 'en',
  /** 1200x630, generated by tools/build-seo.mjs. */
  card: 'assets/og-card.png',
};

export const url = (path = '') =>
  `${SITE.origin}${SITE.base}/${path}`.replace(/\/+$/, path ? '' : '/');

/**
 * Keywords.
 *
 * Search engines have ignored the keywords meta for well over a decade, so it
 * is here for the site's own tooling and for the handful of aggregators that
 * still read it — never as a ranking play. The terms that actually matter are
 * in the title, the description and the visible headings, which is where the
 * exam codes and service names already appear.
 */
const COMMON = [
  'AI-103',
  'AI-103 exam',
  'AI-103 study guide',
  'Developing AI Apps and Agents on Azure',
  'Azure AI Apps and Agents Developer Associate',
  'Microsoft Foundry',
  'Azure AI',
  'Azure certification',
  'Microsoft certification',
];

export const keywords = (extra = []) => [...COMMON, ...extra].join(', ');

function escapeAttr(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Structured data.
 *
 * The guide as a whole is a Course; each module page is a LearningResource
 * that belongs to it. Google understands both, and the pairing is what lets a
 * module page describe itself as part of something larger rather than as a
 * loose article.
 */
export function structuredData({ path, title, description, type = 'page', position }) {
  const author = {
    '@type': 'Person',
    name: SITE.author,
    url: SITE.authorUrl,
  };

  const graph = [];

  if (type === 'home') {
    graph.push({
      '@type': 'WebSite',
      '@id': url() + '#website',
      url: url(),
      name: SITE.name,
      description,
      inLanguage: SITE.locale,
      author,
      publisher: author,
    });
    graph.push({
      '@type': 'Course',
      '@id': url() + '#course',
      name: SITE.name,
      description,
      url: url('guide/index.html'),
      inLanguage: SITE.locale,
      provider: { '@type': 'Person', name: SITE.author, url: SITE.authorUrl },
      author,
      isAccessibleForFree: true,
      teaches: [
        'Plan and manage an Azure AI solution',
        'Implement generative AI and agentic solutions',
        'Implement computer vision solutions',
        'Implement text analysis solutions',
        'Implement information extraction solutions',
      ],
      about: {
        '@type': 'Thing',
        name: 'Microsoft Certified: Azure AI Apps and Agents Developer Associate',
      },
    });
  } else {
    graph.push({
      '@type': type === 'module' ? 'LearningResource' : 'WebPage',
      '@id': url(path) + '#page',
      url: url(path),
      name: title,
      headline: title,
      description,
      inLanguage: SITE.locale,
      author,
      isAccessibleForFree: true,
      isPartOf: { '@id': url() + '#website' },
      ...(type === 'module'
        ? {
            learningResourceType: 'Study guide',
            educationalLevel: 'Intermediate',
            teaches: title,
            partOfCourse: { '@id': url() + '#course' },
          }
        : {}),
    });
  }

  // A breadcrumb trail for anything below the site root.
  if (path) {
    const crumbs = [{ name: 'Home', item: url() }];
    if (path.startsWith('guide/')) crumbs.push({ name: 'Study guide', item: url('guide/index.html') });
    if (path !== 'guide/index.html') crumbs.push({ name: title, item: url(path) });

    graph.push({
      '@type': 'BreadcrumbList',
      itemListElement: crumbs.map((c, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: c.name,
        item: c.item,
      })),
    });
  }

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph });
}

/**
 * Every head tag a page needs beyond charset/viewport/stylesheets.
 *
 * `path` is relative to the site root, e.g. "guide/models.html" or "" for the
 * home page. `up` is the relative prefix back to docs/ for local asset hrefs.
 */
export function metaTags({ path, title, description, extraKeywords = [], type = 'page', up = '' }) {
  const fullTitle = path
    ? `${title} — ${SITE.shortName}`
    : `${SITE.shortName} — ${SITE.tagline}`;
  const canonical = url(path);

  return `<title>${escapeAttr(fullTitle)}</title>
<meta name="description" content="${escapeAttr(description)}">
<meta name="keywords" content="${escapeAttr(keywords(extraKeywords))}">
<meta name="author" content="${escapeAttr(SITE.author)}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<link rel="canonical" href="${canonical}">

<meta property="og:type" content="${path ? 'article' : 'website'}">
<meta property="og:site_name" content="${escapeAttr(SITE.name)}">
<meta property="og:title" content="${escapeAttr(fullTitle)}">
<meta property="og:description" content="${escapeAttr(description)}">
<meta property="og:url" content="${canonical}">
<meta property="og:locale" content="en_GB">
<meta property="og:image" content="${url(SITE.card)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${escapeAttr(SITE.name)} — ${escapeAttr(SITE.tagline)}">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escapeAttr(fullTitle)}">
<meta name="twitter:description" content="${escapeAttr(description)}">
<meta name="twitter:image" content="${url(SITE.card)}">

<meta name="theme-color" content="#0B2136">
<link rel="icon" href="${up}assets/favicon.svg" type="image/svg+xml">

<script type="application/ld+json">${structuredData({ path, title, description, type })}</script>`;
}
